package fsf.beans.info.newstype;

// default package
// Generated 2010-4-29 21:13:29 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;

import fsf.beans.info.news.News;

/**
 * InfoNewsType generated by hbm2java
 */
public class NewsType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4396651234051360581L;
	private Integer newsTypeId;
	private String title;
	private Integer seq;
	private Short status;
	private Date createTime;
	private Integer createUserId;
	private Date updateTime;
	private Integer updateUserId;
	private List<News> listNews;

	public NewsType() {
	}

	public NewsType(String title, Integer seq, Short status, Date createTime,
			Integer createUserId, Date updateTime, Integer updateUserId) {
		this.title = title;
		this.seq = seq;
		this.status = status;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.updateTime = updateTime;
		this.updateUserId = updateUserId;
	}

	public Integer getNewsTypeId() {
		return this.newsTypeId;
	}

	public void setNewsTypeId(Integer newsTypeId) {
		this.newsTypeId = newsTypeId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public List<News> getListNews() {
		return listNews;
	}

	public void setListNews(List<News> listNews) {
		this.listNews = listNews;
	}
}
