package fsf.beans.info.newtype;

// default package
// Generated 2010-4-22 21:14:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * InfoNewType generated by hbm2java
 */
public class NewType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8941661796256914241L;
	private Integer newTypeId;
	private String title;
	private Integer seq;
	private Short status;
	private Date createTime;
	private Integer createUserId;
	private Date modifyTime;
	private Integer modifyUserId;

	public NewType() {
	}

	public NewType(String title, Integer seq, Short status, Date createTime,
			Integer createUserId, Date modifyTime, Integer modifyUserId) {
		this.title = title;
		this.seq = seq;
		this.status = status;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.modifyTime = modifyTime;
		this.modifyUserId = modifyUserId;
	}

	public Integer getNewTypeId() {
		return this.newTypeId;
	}

	public void setNewTypeId(Integer newTypeId) {
		this.newTypeId = newTypeId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Integer modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

}
