package fsf.beans.est.broker;

// default package
// Generated 2010-4-22 21:05:16 by Hibernate Tools 3.2.4.GA

/**
 * EstBroker generated by hbm2java
 */
public class Broker implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7915034102040401592L;
	private Integer userId;
	private String realName;
	private Short status;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;
	private String level;
	private String company;
	private String license;
	private String imagePath;
	private String remark;
	private String hobby;
	private String glory;

	public Broker() {
	}

	public Broker(int userId, String realName, Short status) {
		this.userId = userId;
		this.realName = realName;
		this.status = status;
	}

	public Broker(int userId, String realName, Short status, Integer provinceId,
			Integer cityId, Integer districtId, String level, String company,
			String license, String imagePath, String remark, String hobby,
			String glory) {
		this.userId = userId;
		this.realName = realName;
		this.status = status;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.districtId = districtId;
		this.level = level;
		this.company = company;
		this.license = license;
		this.imagePath = imagePath;
		this.remark = remark;
		this.hobby = hobby;
		this.glory = glory;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getGlory() {
		return this.glory;
	}

	public void setGlory(String glory) {
		this.glory = glory;
	}

}
