package fsf.beans.est.commerce;

// default package
// Generated 2010-4-22 21:00:06 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * EstCommerce generated by hbm2java
 */
public class Commerce implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1990782207194523700L;
	private Integer commerceId;
	private String title;
	private String content;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;
	private Integer areaId;
	private String imagePath;
	/**
	 * 1 - 厂房仓库 2 - 酒楼转让   3 - 写字楼4 - 餐厅转让 5 - 商铺6  - 工厂转让 7 - 美容发廊 8 - 房租转让
	 */
	private Integer commerceType;
	private Short status;
	private String ip;
	private Date createTime;
	private Integer createUserId;
	private Date updateTime;
	private Integer updateUserId;
	private String address;

	public Commerce() {
	}

	public Commerce(String title, String content, Integer commerceType,
			Short status, String ip, Date createTime, Integer createUserId,
			Date updateTime, Integer updateUserId, 
			String address) {
		this.title = title;
		this.content = content;
		this.commerceType = commerceType;
		this.status = status;
		this.ip = ip;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.updateTime = updateTime;
		this.updateUserId = updateUserId;
		this.address = address;
	}

	public Commerce(String title, String content, Integer provinceId,
			Integer cityId, Integer districtId, Integer areaId,
			Integer commerceType, Short status, String ip, Date createTime,
			Integer createUserId, Date updateTime, Integer updateUserId, 
			 String address) {
		this.title = title;
		this.content = content;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.districtId = districtId;
		this.areaId = areaId;
		this.commerceType = commerceType;
		this.status = status;
		this.ip = ip;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.updateTime = updateTime;
		this.updateUserId = updateUserId;
		this.address = address;
	}

	public Integer getCommerceId() {
		return this.commerceId;
	}

	public void setCommerceId(Integer commerceId) {
		this.commerceId = commerceId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public Integer getCommerceType() {
		return this.commerceType;
	}

	public void setCommerceType(Integer commerceType) {
		this.commerceType = commerceType;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((commerceId == null) ? 0 : commerceId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Commerce other = (Commerce) obj;
		if (commerceId == null) {
			if (other.commerceId != null)
				return false;
		} else if (!commerceId.equals(other.commerceId))
			return false;
		return true;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
}
