package fsf.beans.sys.user;

// default package
// Generated 2010-4-21 10:18:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SysUser generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3280045638851221542L;
	private Integer userId;
	private String userCode;
	private String password;
	private String question;
	private String answer;
	private String userName;
	private Short sex;
	private Short status;
	private Short userType;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;
	private String address;
	private String tel;
	private String phone;
	private String qq;
	private String msn;
	private String email;
	private String remark;
	private Date createDate;
	private String imagePath;

	public User() {
	}

	public User(String userCode, String password, Short status, Short userType,
			Date createDate) {
		this.userCode = userCode;
		this.password = password;
		this.status = status;
		this.userType = userType;
		this.createDate = createDate;
	}

	public User(String userCode, String password, String question,
			String answer, String userName, Short sex, Short status,
			Short userType, Integer provinceId, Integer cityId,
			Integer districtId, String address, String tel, String phone,
			String qq, String msn, String email, String remark,
			Date createDate, String imagePath) {
		this.userCode = userCode;
		this.password = password;
		this.question = question;
		this.answer = answer;
		this.userName = userName;
		this.sex = sex;
		this.status = status;
		this.userType = userType;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.districtId = districtId;
		this.address = address;
		this.tel = tel;
		this.phone = phone;
		this.qq = qq;
		this.msn = msn;
		this.email = email;
		this.remark = remark;
		this.createDate = createDate;
		this.imagePath = imagePath;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Short getSex() {
		return this.sex;
	}

	public void setSex(Short sex) {
		this.sex = sex;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Short getUserType() {
		return this.userType;
	}

	public void setUserType(Short userType) {
		this.userType = userType;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
