package fsf.beans.est.newestate;
// default package
// Generated 2010-4-22 21:00:06 by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * EstNewEstate generated by hbm2java
 */
public class NewEstate  implements java.io.Serializable {


     private Integer estateId;
     private String estateName;
     private String develop;
     private Integer provinceId;
     private Integer cityId;
     private Integer districtId;
     private Integer areaId;
     private byte status;
     private byte isHot;
     private byte estateType;
     private BigDecimal area;
     private byte isLift;
     private BigDecimal practicalArea;
     private int effective;
     private String estateAddress;
     private Integer toward;
     private int totalFloor;
     private BigDecimal price;
     private int hall;
     private int bedroom;
     private int toilet;
     private int porch;
     private BigDecimal manageCost;
     private BigDecimal otherCost;
     private byte fitment;
     private String remark;
     private String imagePath;
     private Date createTime;
     private int createUserId;
     private Date updateTime;
     private int updateUserId;

    public NewEstate() {
    }

	
    public NewEstate(byte status, byte isHot, byte estateType, BigDecimal area, byte isLift, BigDecimal practicalArea, int effective, String estateAddress, int totalFloor, int hall, int bedroom, int toilet, int porch, BigDecimal manageCost, byte fitment, Date createTime, int createUserId, Date updateTime, int updateUserId) {
        this.status = status;
        this.isHot = isHot;
        this.estateType = estateType;
        this.area = area;
        this.isLift = isLift;
        this.practicalArea = practicalArea;
        this.effective = effective;
        this.estateAddress = estateAddress;
        this.totalFloor = totalFloor;
        this.hall = hall;
        this.bedroom = bedroom;
        this.toilet = toilet;
        this.porch = porch;
        this.manageCost = manageCost;
        this.fitment = fitment;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.updateTime = updateTime;
        this.updateUserId = updateUserId;
    }
    public NewEstate(String estateName, String develop, Integer provinceId, Integer cityId, Integer districtId, Integer areaId, byte status, byte isHot, byte estateType, BigDecimal area, byte isLift, BigDecimal practicalArea, int effective, String estateAddress, Integer toward, int totalFloor, BigDecimal price, int hall, int bedroom, int toilet, int porch, BigDecimal manageCost, BigDecimal otherCost, byte fitment, String remark, String imagePath, Date createTime, int createUserId, Date updateTime, int updateUserId) {
       this.estateName = estateName;
       this.develop = develop;
       this.provinceId = provinceId;
       this.cityId = cityId;
       this.districtId = districtId;
       this.areaId = areaId;
       this.status = status;
       this.isHot = isHot;
       this.estateType = estateType;
       this.area = area;
       this.isLift = isLift;
       this.practicalArea = practicalArea;
       this.effective = effective;
       this.estateAddress = estateAddress;
       this.toward = toward;
       this.totalFloor = totalFloor;
       this.price = price;
       this.hall = hall;
       this.bedroom = bedroom;
       this.toilet = toilet;
       this.porch = porch;
       this.manageCost = manageCost;
       this.otherCost = otherCost;
       this.fitment = fitment;
       this.remark = remark;
       this.imagePath = imagePath;
       this.createTime = createTime;
       this.createUserId = createUserId;
       this.updateTime = updateTime;
       this.updateUserId = updateUserId;
    }
   
    public Integer getEstateId() {
        return this.estateId;
    }
    
    public void setEstateId(Integer estateId) {
        this.estateId = estateId;
    }
    public String getEstateName() {
        return this.estateName;
    }
    
    public void setEstateName(String estateName) {
        this.estateName = estateName;
    }
    public String getDevelop() {
        return this.develop;
    }
    
    public void setDevelop(String develop) {
        this.develop = develop;
    }
    public Integer getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public Integer getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }
    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public byte getIsHot() {
        return this.isHot;
    }
    
    public void setIsHot(byte isHot) {
        this.isHot = isHot;
    }
    public byte getEstateType() {
        return this.estateType;
    }
    
    public void setEstateType(byte estateType) {
        this.estateType = estateType;
    }
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }
    public byte getIsLift() {
        return this.isLift;
    }
    
    public void setIsLift(byte isLift) {
        this.isLift = isLift;
    }
    public BigDecimal getPracticalArea() {
        return this.practicalArea;
    }
    
    public void setPracticalArea(BigDecimal practicalArea) {
        this.practicalArea = practicalArea;
    }
    public int getEffective() {
        return this.effective;
    }
    
    public void setEffective(int effective) {
        this.effective = effective;
    }
    public String getEstateAddress() {
        return this.estateAddress;
    }
    
    public void setEstateAddress(String estateAddress) {
        this.estateAddress = estateAddress;
    }
    public Integer getToward() {
        return this.toward;
    }
    
    public void setToward(Integer toward) {
        this.toward = toward;
    }
    public int getTotalFloor() {
        return this.totalFloor;
    }
    
    public void setTotalFloor(int totalFloor) {
        this.totalFloor = totalFloor;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public int getHall() {
        return this.hall;
    }
    
    public void setHall(int hall) {
        this.hall = hall;
    }
    public int getBedroom() {
        return this.bedroom;
    }
    
    public void setBedroom(int bedroom) {
        this.bedroom = bedroom;
    }
    public int getToilet() {
        return this.toilet;
    }
    
    public void setToilet(int toilet) {
        this.toilet = toilet;
    }
    public int getPorch() {
        return this.porch;
    }
    
    public void setPorch(int porch) {
        this.porch = porch;
    }
    public BigDecimal getManageCost() {
        return this.manageCost;
    }
    
    public void setManageCost(BigDecimal manageCost) {
        this.manageCost = manageCost;
    }
    public BigDecimal getOtherCost() {
        return this.otherCost;
    }
    
    public void setOtherCost(BigDecimal otherCost) {
        this.otherCost = otherCost;
    }
    public byte getFitment() {
        return this.fitment;
    }
    
    public void setFitment(byte fitment) {
        this.fitment = fitment;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public int getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(int createUserId) {
        this.createUserId = createUserId;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public int getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(int updateUserId) {
        this.updateUserId = updateUserId;
    }




}


