package fsf.beans.est.bussinessarea;

// default package
// Generated 2010-4-22 21:05:16 by Hibernate Tools 3.2.4.GA

/**
 * EstBusinessarea generated by hbm2java
 */
public class Businessarea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8849939018623422870L;
	private Integer areaId;
	private String areaName;
	private Integer districtId;

	public Businessarea() {
	}

	public Businessarea(String areaName, int districtId) {
		this.areaName = areaName;
		this.districtId = districtId;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public int getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

}
