package fsf.beans.est.businessarea;

// default package
// Generated 2010-4-24 10:22:14 by Hibernate Tools 3.2.4.GA

/**
 * EstBusinessarea generated by hbm2java
 */
public class Businessarea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2247567521435189497L;
	private Integer areaId;
	private String areaName;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;

	public Businessarea() {
	}

	public Businessarea(String areaName, Integer provinceId, Integer cityId,
			Integer districtId) {
		this.areaName = areaName;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.districtId = districtId;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

}
