/*
 * JSP generated by Resin-3.0.19 (built Fri, 21 Jul 2006 03:52:09 PDT)
 */

package _jsp._web_22dinf._page;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    org.apache.struts2.views.jsp.SetTag _jsp_SetTag_0 = null;
    org.apache.struts2.views.jsp.TextTag _jsp_TextTag_1 = null;
    org.apache.struts2.views.jsp.ui.FormTag _jsp_FormTag_2 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_3 = null;
    org.apache.struts2.views.jsp.IteratorTag _jsp_IteratorTag_4 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_5 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String contextPath = request.getContextPath();

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((contextPath));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_SetTag_0 == null) {
        _jsp_SetTag_0 = new org.apache.struts2.views.jsp.SetTag();
        _jsp_SetTag_0.setPageContext(pageContext);
        _jsp_SetTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_SetTag_0.setName("contextPath");
        _jsp_SetTag_0.setValue("pageContext.request.comtextPath");
      }

      int _jspEval2 = _jsp_SetTag_0.doStartTag();
      _jsp_SetTag_0.doEndTag();
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_required");
      int _jspEval6 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string4, 0, _jsp_string4.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidNumber");
      int _jspEval10 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_requiredInteger");
      int _jspEval14 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooLong");
      int _jspEval18 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooLarge");
      int _jspEval22 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooSmall");
      int _jspEval26 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_integerTooLong");
      int _jspEval30 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_decimalTooLong");
      int _jspEval34 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidDate");
      int _jspEval38 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string12, 0, _jsp_string12.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidtime");
      int _jspEval42 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidDateTime");
      int _jspEval46 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidEmail");
      int _jspEval50 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string15, 0, _jsp_string15.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_illegalDateTime");
      int _jspEval54 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string16, 0, _jsp_string16.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_confirmDelete");
      int _jspEval58 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((basePath));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack60 = null;
      if (_jsp_FormTag_2 == null) {
        _jsp_FormTag_2 = new org.apache.struts2.views.jsp.ui.FormTag();
        _jsp_FormTag_2.setPageContext(pageContext);
        _jsp_FormTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_2.setTheme("simple");
        _jsp_FormTag_2.setAction("entityList");
        _jsp_FormTag_2.setNamespace("/system");
        _jsp_FormTag_2.setName("formList");
        _jsp_FormTag_2.setId("formList");
      }

      int _jspEval62 = _jsp_FormTag_2.doStartTag();
      if (_jspEval62 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval62 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack60 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_FormTag_2.setBodyContent(_jsp_endTagHack60);
        }
        out.write(_jsp_string20, 0, _jsp_string20.length);
        if (_jsp_PropertyTag_3 == null) {
          _jsp_PropertyTag_3 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_3.setPageContext(pageContext);
          _jsp_PropertyTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
          _jsp_PropertyTag_3.setValue("userName2");
        }

        int _jspEval65 = _jsp_PropertyTag_3.doStartTag();
        _jsp_PropertyTag_3.doEndTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        com.caucho.jsp.BodyContentImpl _jsp_endTagHack67 = null;
        if (_jsp_IteratorTag_4 == null) {
          _jsp_IteratorTag_4 = new org.apache.struts2.views.jsp.IteratorTag();
          _jsp_IteratorTag_4.setPageContext(pageContext);
          _jsp_IteratorTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
          _jsp_IteratorTag_4.setValue("pageView.records");
          _jsp_IteratorTag_4.setId("var");
        }

        int _jspEval69 = _jsp_IteratorTag_4.doStartTag();
        if (_jspEval69 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspEval69 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
            out = pageContext.pushBody();
            _jsp_endTagHack67 = (com.caucho.jsp.BodyContentImpl) out;
            _jsp_IteratorTag_4.setBodyContent(_jsp_endTagHack67);
          }
          do {
            out.write(_jsp_string22, 0, _jsp_string22.length);
            if (_jsp_PropertyTag_5 == null) {
              _jsp_PropertyTag_5 = new org.apache.struts2.views.jsp.PropertyTag();
              _jsp_PropertyTag_5.setPageContext(pageContext);
              _jsp_PropertyTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IteratorTag_4);
            }

            _jsp_PropertyTag_5.setValue("#var.id");
            int _jspEval72 = _jsp_PropertyTag_5.doStartTag();
            _jsp_PropertyTag_5.doEndTag();
            out.write(_jsp_string23, 0, _jsp_string23.length);
            _jsp_PropertyTag_5.setValue("#var.id");
            int _jspEval76 = _jsp_PropertyTag_5.doStartTag();
            _jsp_PropertyTag_5.doEndTag();
            out.write(_jsp_string24, 0, _jsp_string24.length);
            _jsp_PropertyTag_5.setValue("#var.name");
            int _jspEval80 = _jsp_PropertyTag_5.doStartTag();
            _jsp_PropertyTag_5.doEndTag();
            out.write(_jsp_string24, 0, _jsp_string24.length);
            _jsp_PropertyTag_5.setValue("#var.password");
            int _jspEval84 = _jsp_PropertyTag_5.doStartTag();
            _jsp_PropertyTag_5.doEndTag();
            out.write(_jsp_string25, 0, _jsp_string25.length);
          } while (_jsp_IteratorTag_4.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
          if (_jspEval69 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
            out = pageContext.popBody();
        }
        _jsp_IteratorTag_4.doEndTag();
        if (_jsp_endTagHack67 != null) {
          pageContext.releaseBody(_jsp_endTagHack67);
          _jsp_endTagHack67 = null;
        }
        out.write(_jsp_string26, 0, _jsp_string26.length);
        if (_jspEval62 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_FormTag_2.doEndTag();
      if (_jsp_endTagHack60 != null) {
        pageContext.releaseBody(_jsp_endTagHack60);
        _jsp_endTagHack60 = null;
      }
      out.write(_jsp_string27, 0, _jsp_string27.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_SetTag_0 != null)
        _jsp_SetTag_0.release();
      if (_jsp_TextTag_1 != null)
        _jsp_TextTag_1.release();
      if (_jsp_FormTag_2 != null)
        _jsp_FormTag_2.release();
      if (_jsp_PropertyTag_3 != null)
        _jsp_PropertyTag_3.release();
      if (_jsp_IteratorTag_4 != null)
        _jsp_IteratorTag_4.release();
      if (_jsp_PropertyTag_5 != null)
        _jsp_PropertyTag_5.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 4605327950944108036L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/page/index.jsp"), -1352493038908652323L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/page/share/share.jsp"), 200136311028445988L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/lib/struts2-core-2.0.14.jar"), 7634771424812740374L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.SetTag.class, 4796189393604433878L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.TextTag.class, 6411746799760945854L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.PropertyTag.class, -6992710373809213113L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.IteratorTag.class, 2603852380412923973L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.FormTag.class, 6256472905596743242L));
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string18;
  private final static char []_jsp_string22;
  private final static char []_jsp_string24;
  private final static char []_jsp_string14;
  private final static char []_jsp_string23;
  private final static char []_jsp_string12;
  private final static char []_jsp_string21;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string20;
  private final static char []_jsp_string17;
  private final static char []_jsp_string26;
  private final static char []_jsp_string16;
  private final static char []_jsp_string15;
  private final static char []_jsp_string13;
  private final static char []_jsp_string27;
  private final static char []_jsp_string25;
  private final static char []_jsp_string11;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string19;
  static {
    _jsp_string5 = "';\r\nerrorMsg[2] = '".toCharArray();
    _jsp_string18 = "\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n  <head>\r\n    <base href=\"".toCharArray();
    _jsp_string22 = "\r\n				<tr>\r\n					<td><input type=\"checkbox\" value=\"".toCharArray();
    _jsp_string24 = "</td>\r\n					<td>".toCharArray();
    _jsp_string14 = "';\r\nerrorMsg[11] = '".toCharArray();
    _jsp_string23 = "\" name=\"selectedPK\" /></td>\r\n					<td>".toCharArray();
    _jsp_string12 = "';\r\nerrorMsg[9] = '".toCharArray();
    _jsp_string21 = "</td>\r\n				<td>id</td>\r\n				<td>userName</td>\r\n				<td>password</td>\r\n			</tr>\r\n			".toCharArray();
    _jsp_string10 = "';\r\nerrorMsg[7] = '".toCharArray();
    _jsp_string8 = "';\r\nerrorMsg[5] = '".toCharArray();
    _jsp_string6 = "';\r\nerrorMsg[3] = '".toCharArray();
    _jsp_string4 = "';\r\nerrorMsg[1] = '".toCharArray();
    _jsp_string1 = "\r\n<script type=\"text/javascript\">\r\nvar contextPath = \"".toCharArray();
    _jsp_string2 = "\";\r\n</script>\r\n".toCharArray();
    _jsp_string20 = "\r\n		<table border=\"1\" style=\"width: 100%;\">\r\n			<tr>\r\n				<td><input type=\"checkbox\" onclick=\"\" />".toCharArray();
    _jsp_string17 = "';\r\n</script>\r\n".toCharArray();
    _jsp_string26 = "\r\n		</table>\r\n	".toCharArray();
    _jsp_string16 = "';\r\n\r\nvar confirmDelete='".toCharArray();
    _jsp_string15 = "';\r\nerrorMsg[12] = '".toCharArray();
    _jsp_string13 = "';\r\nerrorMsg[10] = '".toCharArray();
    _jsp_string27 = "\r\n  </body>\r\n</html>\r\n".toCharArray();
    _jsp_string25 = "</td>\r\n				</tr>\r\n			".toCharArray();
    _jsp_string11 = "';\r\nerrorMsg[8] = '".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
    _jsp_string3 = "\r\n<script type=\"text/javascript\">\r\nvar errorMsg = [];\r\nerrorMsg[0] = '".toCharArray();
    _jsp_string9 = "';\r\nerrorMsg[6] = '".toCharArray();
    _jsp_string7 = "';\r\nerrorMsg[4] = '".toCharArray();
    _jsp_string19 = "\">\r\n    \r\n    <title>user index</title>\r\n    \r\n	<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n	<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n	<meta http-equiv=\"expires\" content=\"0\">    \r\n	<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n	<meta http-equiv=\"description\" content=\"This is my page\">\r\n	<!--\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n	-->\r\n\r\n  </head>\r\n  \r\n  <body>\r\n    ".toCharArray();
  }
}
