package fsf.beans.sys.city;

// default package
// Generated 2010-4-24 9:01:44 by Hibernate Tools 3.2.4.GA

/**
 * SysCity generated by hbm2java
 */
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1361255185844708709L;
	private Integer cityId;
	private String cityName;
	private String zipCode;
	private int provinceId;

	public City() {
	}

	public City(String cityName, String zipCode, int provinceId) {
		this.cityName = cityName;
		this.zipCode = zipCode;
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public int getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(int provinceId) {
		this.provinceId = provinceId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cityId == null) ? 0 : cityId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final City other = (City) obj;
		if (cityId == null) {
			if (other.cityId != null)
				return false;
		} else if (!cityId.equals(other.cityId))
			return false;
		return true;
	}

}
