package fsf.beans.est.estatein;

// default package
// Generated 2010-4-22 21:00:06 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * EstEstateIn generated by hbm2java
 */
public class EstateIn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1378919663578948445L;
	private Integer estateId;
	private String title;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;
	private Integer areaId;
	private Short tradeMode;
	private Short estateType;
	private Integer buildYear;
	private Integer hall;
	private Integer bedroom;
	private Integer toilet;
	private Integer porch;
	private Integer toward;
	private Double buyPriceFrom;
	private Double buyPriceTo;
	private Double rentPriceFrom;
	private Double rentPriceTo;
	private Double areaFrom;
	private Double areaTo;
	private Short isLift;
	private Short fitment;
	private Short device;
	private String remark;
	private Date createTime;
	private Integer createUserId;
	private Date updateTime;
	private Integer updateUserId;

	public EstateIn() {
	}

	public EstateIn(String title, Short tradeMode, Short estateType, Integer hall,
			Integer bedroom, Integer toilet, Integer porch, Double areaFrom, Double areaTo,
			Short isLift, Short fitment, Short device, Date createTime,
			Integer createUserId, Date updateTime, Integer updateUserId) {
		this.title = title;
		this.tradeMode = tradeMode;
		this.estateType = estateType;
		this.hall = hall;
		this.bedroom = bedroom;
		this.toilet = toilet;
		this.porch = porch;
		this.areaFrom = areaFrom;
		this.areaTo = areaTo;
		this.isLift = isLift;
		this.fitment = fitment;
		this.device = device;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.updateTime = updateTime;
		this.updateUserId = updateUserId;
	}

	public EstateIn(String title, Integer provinceId, Integer cityId,
			Integer districtId, Integer areaId, Short tradeMode,
			Short estateType, Integer buildYear, Integer hall, Integer bedroom,
			int toilet, Integer porch, Integer toward, Double buyPriceFrom,
			Double buyPriceTo, Double rentPriceFrom, Double rentPriceTo,
			Double areaFrom, Double areaTo, Short isLift, Short fitment,
			Short device, String remark, Date createTime, Integer createUserId,
			Date updateTime, Integer updateUserId) {
		this.title = title;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.districtId = districtId;
		this.areaId = areaId;
		this.tradeMode = tradeMode;
		this.estateType = estateType;
		this.buildYear = buildYear;
		this.hall = hall;
		this.bedroom = bedroom;
		this.toilet = toilet;
		this.porch = porch;
		this.toward = toward;
		this.buyPriceFrom = buyPriceFrom;
		this.buyPriceTo = buyPriceTo;
		this.rentPriceFrom = rentPriceFrom;
		this.rentPriceTo = rentPriceTo;
		this.areaFrom = areaFrom;
		this.areaTo = areaTo;
		this.isLift = isLift;
		this.fitment = fitment;
		this.device = device;
		this.remark = remark;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.updateTime = updateTime;
		this.updateUserId = updateUserId;
	}

	public Integer getEstateId() {
		return this.estateId;
	}

	public void setEstateId(Integer estateId) {
		this.estateId = estateId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public Short getTradeMode() {
		return this.tradeMode;
	}

	public void setTradeMode(Short tradeMode) {
		this.tradeMode = tradeMode;
	}

	public Short getEstateType() {
		return this.estateType;
	}

	public void setEstateType(Short estateType) {
		this.estateType = estateType;
	}

	public Integer getBuildYear() {
		return this.buildYear;
	}

	public void setBuildYear(Integer buildYear) {
		this.buildYear = buildYear;
	}

	public Integer getHall() {
		return this.hall;
	}

	public void setHall(Integer hall) {
		this.hall = hall;
	}

	public Integer getBedroom() {
		return this.bedroom;
	}

	public void setBedroom(Integer bedroom) {
		this.bedroom = bedroom;
	}

	public Integer getToilet() {
		return this.toilet;
	}

	public void setToilet(Integer toilet) {
		this.toilet = toilet;
	}

	public Integer getPorch() {
		return this.porch;
	}

	public void setPorch(Integer porch) {
		this.porch = porch;
	}

	public Integer getToward() {
		return this.toward;
	}

	public void setToward(Integer toward) {
		this.toward = toward;
	}

	public Double getBuyPriceFrom() {
		return this.buyPriceFrom;
	}

	public void setBuyPriceFrom(Double buyPriceFrom) {
		this.buyPriceFrom = buyPriceFrom;
	}

	public Double getBuyPriceTo() {
		return this.buyPriceTo;
	}

	public void setBuyPriceTo(Double buyPriceTo) {
		this.buyPriceTo = buyPriceTo;
	}

	public Double getRentPriceFrom() {
		return this.rentPriceFrom;
	}

	public void setRentPriceFrom(Double rentPriceFrom) {
		this.rentPriceFrom = rentPriceFrom;
	}

	public Double getRentPriceTo() {
		return this.rentPriceTo;
	}

	public void setRentPriceTo(Double rentPriceTo) {
		this.rentPriceTo = rentPriceTo;
	}

	public Double getAreaFrom() {
		return this.areaFrom;
	}

	public void setAreaFrom(Double areaFrom) {
		this.areaFrom = areaFrom;
	}

	public Double getAreaTo() {
		return this.areaTo;
	}

	public void setAreaTo(Double areaTo) {
		this.areaTo = areaTo;
	}

	public Short getIsLift() {
		return this.isLift;
	}

	public void setIsLift(Short isLift) {
		this.isLift = isLift;
	}

	public Short getFitment() {
		return this.fitment;
	}

	public void setFitment(Short fitment) {
		this.fitment = fitment;
	}

	public Short getDevice() {
		return this.device;
	}

	public void setDevice(Short device) {
		this.device = device;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdateUserId() {
		return updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}
}
