package fsf.beans.forum;

// Generated 2010-7-24 1:02:08 by Hibernate Tools 3.2.4.GA

/**
 * ForumForums generated by hbm2java
 */
public class ForumForums implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8254903190960134987L;
	private Integer forumId;
	private int categoriesId;
	private String forumName;
	private String forumDesc;
	private Integer forumOrder;
	private int forumTopics;
	private int forumLastPostId;
	private Boolean moderated;

	public ForumForums() {
	}

	public Integer getForumId() {
		return this.forumId;
	}

	public void setForumId(Integer forumId) {
		this.forumId = forumId;
	}

	public int getCategoriesId() {
		return this.categoriesId;
	}

	public void setCategoriesId(int categoriesId) {
		this.categoriesId = categoriesId;
	}

	public String getForumName() {
		return this.forumName;
	}

	public void setForumName(String forumName) {
		this.forumName = forumName;
	}

	public String getForumDesc() {
		return this.forumDesc;
	}

	public void setForumDesc(String forumDesc) {
		this.forumDesc = forumDesc;
	}

	public Integer getForumOrder() {
		return this.forumOrder;
	}

	public void setForumOrder(Integer forumOrder) {
		this.forumOrder = forumOrder;
	}

	public int getForumTopics() {
		return this.forumTopics;
	}

	public void setForumTopics(int forumTopics) {
		this.forumTopics = forumTopics;
	}

	public int getForumLastPostId() {
		return this.forumLastPostId;
	}

	public void setForumLastPostId(int forumLastPostId) {
		this.forumLastPostId = forumLastPostId;
	}

	public Boolean getModerated() {
		return this.moderated;
	}

	public void setModerated(Boolean moderated) {
		this.moderated = moderated;
	}

}
