package fsf.beans.info.information;

// default package
// Generated 2010-4-22 21:14:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * InfoInformation generated by hbm2java
 */
public class Information implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5901007050095620325L;
	private Integer informationId;
	private String informationTitle;
	private String informationContent;
	private Integer informationType;
	private Short status;
	private Date createTime;
	private Integer createUserId;
	private Date updateTime;
	private Integer updateUserId;

	public Information() {
	}

	public Integer getInformationId() {
		return this.informationId;
	}

	public void setInformationId(Integer informationId) {
		this.informationId = informationId;
	}

	public String getInformationTitle() {
		return this.informationTitle;
	}

	public void setInformationTitle(String informationTitle) {
		this.informationTitle = informationTitle;
	}

	public String getInformationContent() {
		return this.informationContent;
	}

	public void setInformationContent(String informationContent) {
		this.informationContent = informationContent;
	}

	public Integer getInformationType() {
		return this.informationType;
	}

	public void setInformationType(Integer informationType) {
		this.informationType = informationType;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

}
