/*
 * JSP generated by Resin-3.0.19 (built Fri, 21 Jul 2006 03:52:09 PDT)
 */

package _jsp._web_22dinf._page._sysadmin._sys._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _usercontent__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    org.apache.struts2.views.jsp.SetTag _jsp_SetTag_0 = null;
    org.apache.struts2.views.jsp.TextTag _jsp_TextTag_1 = null;
    org.apache.struts2.views.jsp.ui.FormTag _jsp_FormTag_2 = null;
    org.apache.struts2.views.jsp.ui.ActionMessageTag _jsp_ActionMessageTag_3 = null;
    org.apache.struts2.views.jsp.ui.ActionErrorTag _jsp_ActionErrorTag_4 = null;
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jsp_FieldErrorTag_5 = null;
    org.apache.struts2.views.jsp.ui.HiddenTag _jsp_HiddenTag_6 = null;
    org.apache.struts2.views.jsp.TextTag _jsp_TextTag_7 = null;
    org.apache.struts2.views.jsp.ui.TextFieldTag _jsp_TextFieldTag_8 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String contextPath = request.getContextPath();

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((contextPath));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_SetTag_0 == null) {
        _jsp_SetTag_0 = new org.apache.struts2.views.jsp.SetTag();
        _jsp_SetTag_0.setPageContext(pageContext);
        _jsp_SetTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_SetTag_0.setName("contextPath");
        _jsp_SetTag_0.setValue("pageContext.request.contextPath");
      }

      int _jspEval2 = _jsp_SetTag_0.doStartTag();
      _jsp_SetTag_0.doEndTag();
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((contextPath ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((contextPath ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_required");
      int _jspEval6 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidNumber");
      int _jspEval10 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_requiredInteger");
      int _jspEval14 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooLong");
      int _jspEval18 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooLarge");
      int _jspEval22 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_tooSmall");
      int _jspEval26 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_integerTooLong");
      int _jspEval30 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string12, 0, _jsp_string12.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_decimalTooLong");
      int _jspEval34 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string13, 0, _jsp_string13.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidDate");
      int _jspEval38 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string14, 0, _jsp_string14.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidtime");
      int _jspEval42 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string15, 0, _jsp_string15.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidDateTime");
      int _jspEval46 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string16, 0, _jsp_string16.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_invalidEmail");
      int _jspEval50 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string17, 0, _jsp_string17.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_illegalDateTime");
      int _jspEval54 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("g_confirmDelete");
      int _jspEval58 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((contextPath));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("contentPageTitle");
      int _jspEval62 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string21, 0, _jsp_string21.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack64 = null;
      if (_jsp_FormTag_2 == null) {
        _jsp_FormTag_2 = new org.apache.struts2.views.jsp.ui.FormTag();
        _jsp_FormTag_2.setPageContext(pageContext);
        _jsp_FormTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_2.setAction("userSave");
        _jsp_FormTag_2.setNamespace("/sysadmin/sys/user");
        _jsp_FormTag_2.setTheme("simple");
        _jsp_FormTag_2.setName("formItem");
        _jsp_FormTag_2.setId("formItem");
        _jsp_FormTag_2.setMethod("post");
        _jsp_FormTag_2.setOnsubmit("return f_validate()");
      }

      int _jspEval66 = _jsp_FormTag_2.doStartTag();
      if (_jspEval66 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval66 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack64 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_FormTag_2.setBodyContent(_jsp_endTagHack64);
        }
        out.write(_jsp_string22, 0, _jsp_string22.length);
        if (_jsp_ActionMessageTag_3 == null) {
          _jsp_ActionMessageTag_3 = new org.apache.struts2.views.jsp.ui.ActionMessageTag();
          _jsp_ActionMessageTag_3.setPageContext(pageContext);
          _jsp_ActionMessageTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
        }

        int _jspEval69 = _jsp_ActionMessageTag_3.doStartTag();
        _jsp_ActionMessageTag_3.doEndTag();
        if (_jsp_ActionErrorTag_4 == null) {
          _jsp_ActionErrorTag_4 = new org.apache.struts2.views.jsp.ui.ActionErrorTag();
          _jsp_ActionErrorTag_4.setPageContext(pageContext);
          _jsp_ActionErrorTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
        }

        int _jspEval73 = _jsp_ActionErrorTag_4.doStartTag();
        _jsp_ActionErrorTag_4.doEndTag();
        if (_jsp_FieldErrorTag_5 == null) {
          _jsp_FieldErrorTag_5 = new org.apache.struts2.views.jsp.ui.FieldErrorTag();
          _jsp_FieldErrorTag_5.setPageContext(pageContext);
          _jsp_FieldErrorTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
        }

        int _jspEval77 = _jsp_FieldErrorTag_5.doStartTag();
        _jsp_FieldErrorTag_5.doEndTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        if (_jsp_HiddenTag_6 == null) {
          _jsp_HiddenTag_6 = new org.apache.struts2.views.jsp.ui.HiddenTag();
          _jsp_HiddenTag_6.setPageContext(pageContext);
          _jsp_HiddenTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
        }

        _jsp_HiddenTag_6.setName("cmd");
        int _jspEval81 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter.currentPage");
        int _jspEval85 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter.maxResults");
        int _jspEval89 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_userId");
        int _jspEval93 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_userCode");
        int _jspEval97 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_password");
        int _jspEval101 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_userName");
        int _jspEval105 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_status");
        int _jspEval109 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_userType");
        int _jspEval113 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_provinceId");
        int _jspEval117 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_cityId");
        int _jspEval121 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._ne_regionId");
        int _jspEval125 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_address");
        int _jspEval129 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_tel");
        int _jspEval133 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_email");
        int _jspEval137 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._de_createDate");
        int _jspEval141 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_HiddenTag_6.setName("userParameter._se_imagePath");
        int _jspEval145 = _jsp_HiddenTag_6.doStartTag();
        _jsp_HiddenTag_6.doEndTag();
        out.write(_jsp_string25, 0, _jsp_string25.length);
        if (_jsp_TextTag_7 == null) {
          _jsp_TextTag_7 = new org.apache.struts2.views.jsp.TextTag();
          _jsp_TextTag_7.setPageContext(pageContext);
          _jsp_TextTag_7.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
        }

        _jsp_TextTag_7.setName("contentTitle");
        int _jspEval149 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string26, 0, _jsp_string26.length);
        _jsp_TextTag_7.setName("userId");
        int _jspEval153 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        if (_jsp_TextFieldTag_8 == null) {
          _jsp_TextFieldTag_8 = new org.apache.struts2.views.jsp.ui.TextFieldTag();
          _jsp_TextFieldTag_8.setPageContext(pageContext);
          _jsp_TextFieldTag_8.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_2);
          _jsp_TextFieldTag_8.setCssClass("input_text");
        }

        _jsp_TextFieldTag_8.setName("userId");
        int _jspEval157 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("userCode");
        int _jspEval161 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("userCode");
        int _jspEval165 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("password");
        int _jspEval169 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("password");
        int _jspEval173 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("userName");
        int _jspEval177 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("userName");
        int _jspEval181 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("status");
        int _jspEval185 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("status");
        int _jspEval189 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("userType");
        int _jspEval193 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("userType");
        int _jspEval197 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("provinceId");
        int _jspEval201 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("provinceId");
        int _jspEval205 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("cityId");
        int _jspEval209 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("cityId");
        int _jspEval213 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("regionId");
        int _jspEval217 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("regionId");
        int _jspEval221 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("address");
        int _jspEval225 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("address");
        int _jspEval229 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("tel");
        int _jspEval233 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("tel");
        int _jspEval237 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("email");
        int _jspEval241 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("email");
        int _jspEval245 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_TextTag_7.setName("createDate");
        int _jspEval249 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("createDate");
        int _jspEval253 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _jsp_TextTag_7.setName("imagePath");
        int _jspEval257 = _jsp_TextTag_7.doStartTag();
        _jsp_TextTag_7.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _jsp_TextFieldTag_8.setName("imagePath");
        int _jspEval261 = _jsp_TextFieldTag_8.doStartTag();
        _jsp_TextFieldTag_8.doEndTag();
        out.write(_jsp_string30, 0, _jsp_string30.length);
        if (_jspEval66 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_FormTag_2.doEndTag();
      if (_jsp_endTagHack64 != null) {
        pageContext.releaseBody(_jsp_endTagHack64);
        _jsp_endTagHack64 = null;
      }
      out.write(_jsp_string31, 0, _jsp_string31.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("userId");
      int _jspEval266 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string32, 0, _jsp_string32.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("userCode");
      int _jspEval270 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string33, 0, _jsp_string33.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("password");
      int _jspEval274 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string34, 0, _jsp_string34.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("userName");
      int _jspEval278 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string35, 0, _jsp_string35.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("status");
      int _jspEval282 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string36, 0, _jsp_string36.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("userType");
      int _jspEval286 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string37, 0, _jsp_string37.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("provinceId");
      int _jspEval290 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string38, 0, _jsp_string38.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("cityId");
      int _jspEval294 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string39, 0, _jsp_string39.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("regionId");
      int _jspEval298 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string40, 0, _jsp_string40.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("address");
      int _jspEval302 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string41, 0, _jsp_string41.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("tel");
      int _jspEval306 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string42, 0, _jsp_string42.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("email");
      int _jspEval310 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string43, 0, _jsp_string43.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("createDate");
      int _jspEval314 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string44, 0, _jsp_string44.length);
      if (_jsp_TextTag_1 == null) {
        _jsp_TextTag_1 = new org.apache.struts2.views.jsp.TextTag();
        _jsp_TextTag_1.setPageContext(pageContext);
        _jsp_TextTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_TextTag_1.setName("imagePath");
      int _jspEval318 = _jsp_TextTag_1.doStartTag();
      _jsp_TextTag_1.doEndTag();
      out.write(_jsp_string45, 0, _jsp_string45.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_SetTag_0 != null)
        _jsp_SetTag_0.release();
      if (_jsp_TextTag_1 != null)
        _jsp_TextTag_1.release();
      if (_jsp_FormTag_2 != null)
        _jsp_FormTag_2.release();
      if (_jsp_ActionMessageTag_3 != null)
        _jsp_ActionMessageTag_3.release();
      if (_jsp_ActionErrorTag_4 != null)
        _jsp_ActionErrorTag_4.release();
      if (_jsp_FieldErrorTag_5 != null)
        _jsp_FieldErrorTag_5.release();
      if (_jsp_HiddenTag_6 != null)
        _jsp_HiddenTag_6.release();
      if (_jsp_TextTag_7 != null)
        _jsp_TextTag_7.release();
      if (_jsp_TextFieldTag_8 != null)
        _jsp_TextFieldTag_8.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 4605327950944108036L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/page/sysadmin/sys/user/userContent.jsp"), -8449793731193655335L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("share/share.jsp"), -3494377239763852437L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("share/validate.jsp"), -27358581411059782L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/lib/struts2-core-2.0.14.jar"), 7634771424812740374L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.SetTag.class, 4796189393604433878L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.TextTag.class, 6411746799760945854L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.ActionMessageTag.class, 2825277145342211859L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.ActionErrorTag.class, -8859130580918526630L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.FieldErrorTag.class, 5321661233300755168L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.HiddenTag.class, -2119688072483713512L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.TextFieldTag.class, 721534765079456884L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.FormTag.class, 6256472905596743242L));
  }

  private final static char []_jsp_string36;
  private final static char []_jsp_string43;
  private final static char []_jsp_string19;
  private final static char []_jsp_string33;
  private final static char []_jsp_string39;
  private final static char []_jsp_string30;
  private final static char []_jsp_string3;
  private final static char []_jsp_string27;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string26;
  private final static char []_jsp_string10;
  private final static char []_jsp_string24;
  private final static char []_jsp_string25;
  private final static char []_jsp_string6;
  private final static char []_jsp_string41;
  private final static char []_jsp_string40;
  private final static char []_jsp_string44;
  private final static char []_jsp_string2;
  private final static char []_jsp_string28;
  private final static char []_jsp_string22;
  private final static char []_jsp_string18;
  private final static char []_jsp_string21;
  private final static char []_jsp_string15;
  private final static char []_jsp_string37;
  private final static char []_jsp_string11;
  private final static char []_jsp_string20;
  private final static char []_jsp_string7;
  private final static char []_jsp_string42;
  private final static char []_jsp_string31;
  private final static char []_jsp_string45;
  private final static char []_jsp_string34;
  private final static char []_jsp_string16;
  private final static char []_jsp_string12;
  private final static char []_jsp_string23;
  private final static char []_jsp_string5;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string32;
  private final static char []_jsp_string17;
  private final static char []_jsp_string38;
  private final static char []_jsp_string29;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string35;
  static {
    _jsp_string36 = "\",\"Integer\",false,3);\r\n	addfield(\"userType\",\"".toCharArray();
    _jsp_string43 = "\",\"String\",true,80);\r\n	addfield(\"createDate\",\"".toCharArray();
    _jsp_string19 = "';\r\n</script>\r\n<link href=\"".toCharArray();
    _jsp_string33 = "\",\"String\",false,50);\r\n	addfield(\"password\",\"".toCharArray();
    _jsp_string39 = "\",\"Integer\",true,10);\r\n	addfield(\"regionId\",\"".toCharArray();
    _jsp_string30 = "					</td>\r\n				</tr>\r\n			</table>\r\n		</td>\r\n	</tr>\r\n</table>\r\n".toCharArray();
    _jsp_string3 = "\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string27 = ":\r\n					</td>\r\n					<td>\r\n						".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n\r\n".toCharArray();
    _jsp_string14 = "';\r\nerrorMsg[9] = '".toCharArray();
    _jsp_string26 = "</span>\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td>\r\n			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n				<tr>\r\n					<td class=\"input_name\">\r\n						".toCharArray();
    _jsp_string10 = "';\r\nerrorMsg[5] = '".toCharArray();
    _jsp_string24 = "\r\n".toCharArray();
    _jsp_string25 = "\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n	<tr>\r\n		<td valign=\"middle\">\r\n			<input type=\"button\" onclick=\"g_save()\" value=\"save\">\r\n			<input type=\"button\" onclick=\"g_back('/sysadmin/sys/user/userList.action')\" value=\"back\">\r\n		</td>\r\n	</tr>\r\n</table>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"content_tbl\">\r\n	<tr>\r\n		<td height=\"21\" class=\"title\">\r\n			<span class=\"title_font\">".toCharArray();
    _jsp_string6 = "';\r\nerrorMsg[1] = '".toCharArray();
    _jsp_string41 = "\",\"String\",true,200);\r\n	addfield(\"tel\",\"".toCharArray();
    _jsp_string40 = "\",\"Integer\",true,10);\r\n	addfield(\"address\",\"".toCharArray();
    _jsp_string44 = "\",\"Date\",false,19);\r\n	addfield(\"imagePath\",\"".toCharArray();
    _jsp_string2 = "\";\r\n</script>\r\n".toCharArray();
    _jsp_string28 = "<font color=\"red\">*</font>\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td class=\"input_name\">\r\n						".toCharArray();
    _jsp_string22 = "\r\n<div id=\"errorMsg\" class=\"errorMsg\">".toCharArray();
    _jsp_string18 = "';\r\n\r\nvar confirmDelete='".toCharArray();
    _jsp_string21 = "</title>\r\n</head>\r\n<body>\r\n".toCharArray();
    _jsp_string15 = "';\r\nerrorMsg[10] = '".toCharArray();
    _jsp_string37 = "\",\"Integer\",false,3);\r\n	addfield(\"provinceId\",\"".toCharArray();
    _jsp_string11 = "';\r\nerrorMsg[6] = '".toCharArray();
    _jsp_string20 = "/css/common.css\" rel=\"stylesheet\"	type=\"text/css\" />\r\n<title>".toCharArray();
    _jsp_string7 = "';\r\nerrorMsg[2] = '".toCharArray();
    _jsp_string42 = "\",\"String\",true,20);\r\n	addfield(\"email\",\"".toCharArray();
    _jsp_string31 = "\r\n</body>\r\n</html>\r\n<script type=\"text/javascript\">\r\nfunction f_validate(){\r\n	fromName = \"formItem\";\r\n	//addfield(\"userId\",\"".toCharArray();
    _jsp_string45 = "\",\"String\",true,100);\r\n	return validate();\r\n}\r\n</script>".toCharArray();
    _jsp_string34 = "\",\"String\",false,50);\r\n	addfield(\"userName\",\"".toCharArray();
    _jsp_string16 = "';\r\nerrorMsg[11] = '".toCharArray();
    _jsp_string12 = "';\r\nerrorMsg[7] = '".toCharArray();
    _jsp_string23 = "</div>\r\n".toCharArray();
    _jsp_string5 = "/staticfile/js/share/validate.js\"></script>\r\n<script type=\"text/javascript\">\r\nvar errorMsg = [];\r\nerrorMsg[0] = '".toCharArray();
    _jsp_string8 = "';\r\nerrorMsg[3] = '".toCharArray();
    _jsp_string1 = "\r\n<script type=\"text/javascript\">\r\nvar contextPath = \"".toCharArray();
    _jsp_string32 = "\",\"Integer\",false,10);\r\n	addfield(\"userCode\",\"".toCharArray();
    _jsp_string17 = "';\r\nerrorMsg[12] = '".toCharArray();
    _jsp_string38 = "\",\"Integer\",true,10);\r\n	addfield(\"cityId\",\"".toCharArray();
    _jsp_string29 = "					</td>\r\n				</tr>\r\n				<tr>\r\n					<td class=\"input_name\">\r\n						".toCharArray();
    _jsp_string13 = "';\r\nerrorMsg[8] = '".toCharArray();
    _jsp_string4 = "/staticfile/js/share/share.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string9 = "';\r\nerrorMsg[4] = '".toCharArray();
    _jsp_string35 = "\",\"String\",true,50);\r\n	addfield(\"status\",\"".toCharArray();
  }
}
