package fsf.beans.info.information;

// default package
// Generated 2010-4-22 21:14:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * InfoInformation generated by hbm2java
 */
public class Information implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5901007050095620325L;
	private Integer informationId;
	private String informationTitle;
	private String informationContent;
	private Short isNew;
	private Integer informationType;
	private Short status;
	private Date createTime;
	private Integer createUserId;
	private Date modifyTime;
	private Integer modifyUserId;

	public Information() {
	}

	public Information(String informationTitle, String informationContent,
			Short isNew, Integer informationType, Short status,
			Date createTime, Integer createUserId, Date modifyTime,
			Integer modifyUserId) {
		this.informationTitle = informationTitle;
		this.informationContent = informationContent;
		this.isNew = isNew;
		this.informationType = informationType;
		this.status = status;
		this.createTime = createTime;
		this.createUserId = createUserId;
		this.modifyTime = modifyTime;
		this.modifyUserId = modifyUserId;
	}

	public Integer getInformationId() {
		return this.informationId;
	}

	public void setInformationId(Integer informationId) {
		this.informationId = informationId;
	}

	public String getInformationTitle() {
		return this.informationTitle;
	}

	public void setInformationTitle(String informationTitle) {
		this.informationTitle = informationTitle;
	}

	public String getInformationContent() {
		return this.informationContent;
	}

	public void setInformationContent(String informationContent) {
		this.informationContent = informationContent;
	}

	public Short getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Short isNew) {
		this.isNew = isNew;
	}

	public Integer getInformationType() {
		return this.informationType;
	}

	public void setInformationType(Integer informationType) {
		this.informationType = informationType;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Integer modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

}
