package fsf.beans.est.newestate;

// default package
// Generated 2010-4-22 21:00:06 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * EstNewEstate generated by hbm2java
 */
public class NewEstate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7202519801729157760L;
	private Integer estateId;
	private String estateName;
	private String develop;
	private Integer provinceId;
	private Integer cityId;
	private Integer districtId;
	private Integer areaId;
	private Short status;
	private Short isHot;
	private Short estateType;
	private Double area;
	private Short isLift;
	private Double practicalArea;
	private Integer effective;
	private String address;
	private Integer toward;
	private Integer totalFloor;
	private Double price;
	private Integer hall;
	private Integer bedroom;
	private Integer toilet;
	private Integer porch;
	private Double manageCost;
	private Double otherCost;
	private Short fitment;
	private String remark;
	private String imagePath;
	private Date createTime;
	private Integer createUserId;
	private Date updateTime;
	private Integer updateUserId;

	public NewEstate() {
	}

	public Integer getEstateId() {
		return this.estateId;
	}

	public void setEstateId(Integer estateId) {
		this.estateId = estateId;
	}

	public String getEstateName() {
		return this.estateName;
	}

	public void setEstateName(String estateName) {
		this.estateName = estateName;
	}

	public String getDevelop() {
		return this.develop;
	}

	public void setDevelop(String develop) {
		this.develop = develop;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Short getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Short isHot) {
		this.isHot = isHot;
	}

	public Short getEstateType() {
		return this.estateType;
	}

	public void setEstateType(Short estateType) {
		this.estateType = estateType;
	}

	public Double getArea() {
		return this.area;
	}

	public void setArea(Double area) {
		this.area = area;
	}

	public Short getIsLift() {
		return this.isLift;
	}

	public void setIsLift(Short isLift) {
		this.isLift = isLift;
	}

	public Double getPracticalArea() {
		return this.practicalArea;
	}

	public void setPracticalArea(Double practicalArea) {
		this.practicalArea = practicalArea;
	}

	public Integer getEffective() {
		return this.effective;
	}

	public void setEffective(Integer effective) {
		this.effective = effective;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getToward() {
		return this.toward;
	}

	public void setToward(Integer toward) {
		this.toward = toward;
	}

	public Integer getTotalFloor() {
		return this.totalFloor;
	}

	public void setTotalFloor(Integer totalFloor) {
		this.totalFloor = totalFloor;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getHall() {
		return this.hall;
	}

	public void setHall(Integer hall) {
		this.hall = hall;
	}

	public Integer getBedroom() {
		return this.bedroom;
	}

	public void setBedroom(Integer bedroom) {
		this.bedroom = bedroom;
	}

	public Integer getToilet() {
		return this.toilet;
	}

	public void setToilet(Integer toilet) {
		this.toilet = toilet;
	}

	public Integer getPorch() {
		return this.porch;
	}

	public void setPorch(Integer porch) {
		this.porch = porch;
	}

	public Double getManageCost() {
		return this.manageCost;
	}

	public void setManageCost(Double manageCost) {
		this.manageCost = manageCost;
	}

	public Double getOtherCost() {
		return this.otherCost;
	}

	public void setOtherCost(Double otherCost) {
		this.otherCost = otherCost;
	}

	public Short getFitment() {
		return this.fitment;
	}

	public void setFitment(Short fitment) {
		this.fitment = fitment;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

}
