package fsf.beans.sys.pageinfo;

// default package
// Generated 2010-7-4 17:25:30 by Hibernate Tools 3.2.4.GA

/**
 * SysPageInfo generated by hbm2java
 */
public class PageInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1612550646479020470L;
	private String infoName;
	private String infoDesc;
	private String title;
	private String content;
	private Byte seq;

	public PageInfo() {
	}

	public PageInfo(String infoName) {
		this.infoName = infoName;
	}

	public PageInfo(String infoName, String infoDesc, String title,
			String content, Byte seq) {
		this.infoName = infoName;
		this.infoDesc = infoDesc;
		this.title = title;
		this.content = content;
		this.seq = seq;
	}

	public String getInfoName() {
		return this.infoName;
	}

	public void setInfoName(String infoName) {
		this.infoName = infoName;
	}

	public String getInfoDesc() {
		return this.infoDesc;
	}

	public void setInfoDesc(String infoDesc) {
		this.infoDesc = infoDesc;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Byte getSeq() {
		return this.seq;
	}

	public void setSeq(Byte seq) {
		this.seq = seq;
	}

}
