package fsf.beans.est.palace;
// default package
// Generated 2010-4-22 21:00:06 by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * EstPalace generated by hbm2java
 */
public class Palace  implements java.io.Serializable {


     private Integer palaceId;
     private String palaceName;
     private String palaceAddress;
     private String palaceDesc;
     private byte status;
     private Date createTime;
     private int createUserId;
     private Date updateTime;
     private int updateUserId;

    public Palace() {
    }

	
    public Palace(String palaceName, byte status, Date createTime, int createUserId, Date updateTime, int updateUserId) {
        this.palaceName = palaceName;
        this.status = status;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.updateTime = updateTime;
        this.updateUserId = updateUserId;
    }
    public Palace(String palaceName, String palaceAddress, String palaceDesc, byte status, Date createTime, int createUserId, Date updateTime, int updateUserId) {
       this.palaceName = palaceName;
       this.palaceAddress = palaceAddress;
       this.palaceDesc = palaceDesc;
       this.status = status;
       this.createTime = createTime;
       this.createUserId = createUserId;
       this.updateTime = updateTime;
       this.updateUserId = updateUserId;
    }
   
    public Integer getPalaceId() {
        return this.palaceId;
    }
    
    public void setPalaceId(Integer palaceId) {
        this.palaceId = palaceId;
    }
    public String getPalaceName() {
        return this.palaceName;
    }
    
    public void setPalaceName(String palaceName) {
        this.palaceName = palaceName;
    }
    public String getPalaceAddress() {
        return this.palaceAddress;
    }
    
    public void setPalaceAddress(String palaceAddress) {
        this.palaceAddress = palaceAddress;
    }
    public String getPalaceDesc() {
        return this.palaceDesc;
    }
    
    public void setPalaceDesc(String palaceDesc) {
        this.palaceDesc = palaceDesc;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public int getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(int createUserId) {
        this.createUserId = createUserId;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public int getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(int updateUserId) {
        this.updateUserId = updateUserId;
    }




}


